### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by kiniv** [a2ndrade/q-intellij-plugin#20]
It seems parser fails when sees that q code
(types;separator) 0:/: listofdata

P.S. absolutely amazing plugin!

**Comment by a2ndrade** [comment]
@kiniv thanks!. The fix should be available (through IntelliJ) in a couple of days.

**Comment by kiniv** [comment]
@a2ndrade thanks! Already in the Repo!
I can’t understand why it’s [0-6]: though. 
I only know 0: 1: 2: 

On another topic. I think there are few issues with parsing timestamps and timespans. 
I’m still going through different cases.
What do you prefer: raising one issue with all cases or one by one?
Some cases simple enough so I can change k.flex myself. Would you be ok with that?

**Comment by a2ndrade** [comment]
You're right, `[0-6]:` are all available in k3, not in q/k4. Since the plugin started as a k3/k4/q plugin, some things need cleanup. Please feel free to open PRs with improvements/fixes/tests. Let me know if you have trouble setting a development environment (for you to test your changes).

Thanks!

**Comment by kiniv** [comment]
@a2ndrade thanks, I know how to setup environment to compile plugin, but I'm not entirely sure how to setup debugging profile. So to debug I need compile and restart. Which is a bit annoying. 

So far I noticed following issues with basic types:
1) timestamp and timespan is not supported 
2) there are some false positives. When plugin shows that something 1.5i or 12.01.01 is valid datatype. Which in fact q does not support. I'm willing to make some changes, but wondering what is the best approach. Doing small changes one by one or just one large PR?

Once again, plugin is absolutely awesome. 
Thanks!

**Comment by a2ndrade** [comment]
One PR would be fine. Also, there are a bunch of parsing tests so we'd want to add tests (see/run `QParserTest`) for each of the missing cases. Thanks! 

To debug, there's an Intellij option to debug a plugin (it's one of the debug/target types). I think if you select it, it automatically associate it with the current project. When you run/debug, a new Intellij instance is started.
