### ISSUE TITLE
Rename of a function does not update indices: usages and Ctrl+Click are not working after rename

### ISSUE THREAD

**Issue by YuriyYatsyk** [a2ndrade/q-intellij-plugin#25]
[t1.q.txt](https://github.com/a2ndrade/q-intellij-plugin/files/2470397/t1.q.txt)
[t2.q.txt](https://github.com/a2ndrade/q-intellij-plugin/files/2470398/t2.q.txt)

First, thanks for developing awesome plugin!

Now to the issue: using version 1.5 of the plugin. Please use attached files to reproduce. Do F6, rename f1 in t1.q to f3. The rename works correctly - both function definition and all usages are updated correctly. However, if I try to find usages of f3 now, nothing's found. Ctrl+Click on invocation of f3 does not work either.

**Comment by a2ndrade** [comment]
@YuriyYatsyk thanks for the report. I knew about this issue. I pushed a _fix_ (will be available in v1.6 in a few days). Hopefully, it'll make it work. 

The underlying issue/challenge is that I have a few caches to speed up reference resolution & autocomplete but the cache invalidation depends on IntelliJ notifying the plugin of file changes and IntelliJ batches updates and sometimes doesn't report file changes if those are fairly small (as in your sample files). At some point, it eventually does it (notifies the plugin) but it's not deterministic.

**Comment by a2ndrade** [comment]
Fixed on v1.6+

**Comment by YuriyYatsyk** [comment]
Thanks for the fix, works now.
