### ISSUE TITLE
Control flow keywords are flagged as undefined variables, not highlighted as keywords when followed by whitespace

### ISSUE THREAD

**Issue by YuriyYatsyk** [a2ndrade/q-intellij-plugin#28]
Using v1.7

while/do/if in the sample below will be flagged as potentially uninitialized variables instead of being treated as keywords. Works correctly if there is no space between keyword and open bracket [.

i:0;
while [i<3; i+:1];

do [3; i+:1];

if [i>5; 0N!i];

**Comment by a2ndrade** [comment]
In this case, the plugin behavior is correct. `if/while/do` are only treated as keywords when they are immediately followed by `[`, otherwise they are just like any other identifier. For example, this is all valid:
```q
while:1;
do:2;
if:3;
while+do+if
```

**Comment by YuriyYatsyk** [comment]
Hmm, perhaps, but the code with spaces is also valid and they are treated as keywords...

________________________________

**Comment by a2ndrade** [comment]
Actually, you're right. I'm quoting behavior from k3 (the plugin originally supported both k3 & q/k4) but q/k4 treat whitespaces differently than k3.
