### ISSUE TITLE
Ctrl+Click navigation/find references does not work after Undo (Ctrl+z)

### ISSUE THREAD

**Issue by YuriyYatsyk** [a2ndrade/q-intellij-plugin#29]
Using v1.7.

To reproduce - rename a function, undo rename (Ctrl+Z) - Ctrl+Click & Alt+F7 stop working.

**Comment by a2ndrade** [comment]
I think this bug has always been there. I haven't found a way to hook into the undo action yet. I may look into this in the future. Thanks for the bug report.

**Comment by a2ndrade** [comment]
Fixed in v1.22
