### ISSUE TITLE
Autocomplete suggestions include duplicate entries if a global with the same name is defined in multiple files

### ISSUE THREAD

**Issue by YuriyYatsyk** [a2ndrade/q-intellij-plugin#30]
Just like stated in the description - if a project has global variable defined in multiple files (legitimate use case for this is when you have multiple "main" scripts), all instances will appear in autocomplete suggestions. This is not really necessary and can be inconvenient.

**Comment by a2ndrade** [comment]
Thanks for the bug report. I'll include a fix for this in the next release (sometime in Nov.)

**Comment by a2ndrade** [comment]
@YuriyYatsyk thanks for the fix/contribution! I'll address #31 and #28 and ship a new version with all 3 issues fixed.
