### ISSUE TITLE
Deleting namespace (\d) instruction does not update structure view

### ISSUE THREAD

**Issue by YuriyYatsyk** [a2ndrade/q-intellij-plugin#43]
Steps to reproduce:

1) define a function
2) insert \d instruction before the function - observe structure view update function name with namespace
3) delete \d instruction from the file completely - structure view still shows function name with namespace.

**Comment by YuriyYatsyk** [comment]
![nsbug](https://user-images.githubusercontent.com/44070801/64748172-2b413500-d4df-11e9-9f3f-b957c917b00e.png)

**Comment by a2ndrade** [comment]
Thanks, @YuriyYatsyk. Do you how to fix it? There's a delay on the editor changes (controlled by Intellij). Do you know if the structure view is eventually updated (after some time) or is it never updated?

**Comment by YuriyYatsyk** [comment]
Don’t know how to fix. Never updated.

**Comment by a2ndrade** [comment]
Fixed in v1.22
