### ISSUE TITLE
Find usages does not work across modules

### ISSUE THREAD

**Issue by YuriyYatsyk** [a2ndrade/q-intellij-plugin#45]
See attached picture for steps to reproduce
![modules_bug](https://user-images.githubusercontent.com/44070801/65649508-d3252b00-dfd4-11e9-892c-41912bc8903b.png)
.

**Comment by YuriyYatsyk** [comment]
@a2ndrade FYI

**Comment by a2ndrade** [comment]
@YuriyYatsyk could you verify this is fixed in 1.19?

**Comment by YuriyYatsyk** [comment]
Will do

**Comment by YuriyYatsyk** [comment]
Works great now, thanks!
