### ISSUE TITLE
Function defined in a different module is erroneously flagged as 'might not have been defined'

### ISSUE THREAD

**Issue by YuriyYatsyk** [a2ndrade/q-intellij-plugin#46]
![modules_bug2](https://user-images.githubusercontent.com/44070801/65649531-efc16300-dfd4-11e9-8592-387386810612.png)

**Comment by a2ndrade** [comment]
@YuriyYatsyk this may have been fixed by 1.19. Could you test it? thanks!

**Comment by YuriyYatsyk** [comment]
Will do

**Comment by YuriyYatsyk** [comment]
It is, indeed, fixed, thanks!
