### ISSUE TITLE
Add support of execution current line on a server

### ISSUE THREAD

**Issue by bulkon** [a2ndrade/q-intellij-plugin#48]
It would be great if q plugin supported execution of current line on a remote server as it'd reduce number of actions needed to achieve that. Now it requires: Ctrl+c, Ctrl+Alt+e. Single shortcut would be awesome

**Comment by a2ndrade** [comment]
Thanks. I'll consider this in the next version/upgrade. Maybe a new action could be added (without a shortcut) for "Evaluating current line" and then you could pick any shortcut you wanted so that we avoid adding more shortcuts that may conflict with other plugins.

**Comment by a2ndrade** [comment]
@YuriyYatsyk FYI

**Comment by bulkon** [comment]
Thanks a lot. Almost any tool working with q (qPad, kdb studio, Sublime q
plugin) has that feature so colleagues and I are missing it a lot. By the
way wanted to say thank you for the plugin  you're developing. Due to your
plugin Idea became the most used IDE for development. Code analyzer is the
best among other solutions.

чт, 17 окт. 2019 г., 23:28 Antonio Andrade <notifications@github.com>:

**Comment by YuriyYatsyk** [comment]
@a2ndrade @CTAJINH 

What if we extend the existing 'Evaluate Selection' shortcut to run current line if there's no selection?

So menu will either be 'Evaluate Selection On' or 'Evaluate Current Line On', depending on if anything is selected or not, and will use the same shortcut.

Thoughts?

**Comment by bulkon** [comment]
It makes perfect sense for me. Should be handy

ср, 30 окт. 2019 г., 7:21 Yuriy Yatsyk <notifications@github.com>:

**Comment by a2ndrade** [comment]
Merged to 1.20. It should be available in a couple of days. Thanks, @YuriyYatsyk !
