### ISSUE TITLE
Latest plugin is broken

### ISSUE THREAD

**Issue by wibotwi** [a2ndrade/q-intellij-plugin#55]
I am confused about version. On https://plugins.jetbrains.com/plugin/7925-q it says latest is 1.24 released April 21 2020.
But inside PyCharm it shows: plugin version 1.9 and released April 20 2020. 

Anyways, the bug is:
ctrl+shift+f popup dialogue is not working. It keeps flickering "Nothing to show" (liek 5 times per second).
If I click "Open in Find Window" I immediately see result.

**Comment by wibotwi** [comment]
i tried downloading 1.23 zip file directly from plugins.jetbrain.com.  And it did not start, it complains that plugin q requires "modules.java" which is not installed.
Maybe I was indeed using 1.9? Which is latest compatible with PyCharm?

**Comment by a2ndrade** [comment]
Thanks for the bug report. 1.9 is a _really_ old version. I did not realize `PyCharm` was compatible up to that version. I should be able to fix that. The confusing `April 20, 2020` is probably due to timezone differences because I see this:
<img width="190" alt="Screen Shot 2020-04-27 at 8 43 12 PM" src="https://user-images.githubusercontent.com/360167/80434553-0f509f00-88c8-11ea-867f-85624762d351.png">

**Comment by wibotwi** [comment]
Or maybe it's when Pycharm was updated.

**Comment by wibotwi** [comment]
I managed to fix the issue!
I opened jar file from latest 1.24 version.
Inside it I deleted line 
`  <depends>com.intellij.modules.java</depends>`
and now PyCharm starts, and everything works great!!!

**Comment by a2ndrade** [comment]
Thanks for the info! That dependency was added right after `1.9` due to an internal change in the build process for Intellij plugins but I wasn't expecting it to _force_ other editors into that version.

**Comment by wibotwi** [comment]
So if you remove it -> all other Jetbrains products will got new plugin :)

So far I found one great feature: it now understands definitions of globals inside functions. The 1.9 was complaining that var is not defined. :)

**Comment by wibotwi** [comment]
One issue is still not resolved: it does not parse file names with dot.
For example file name "load.q" is parsed and "data.load.q" is not parsed.
I have syntax highlighting in it, but ctrl+click does not navigate to functions defined in that file.

**Comment by a2ndrade** [comment]
That's really odd (that exists and that no one had reported it). Please let me know of anything else you come across so I can take a look. Thanks

**Comment by wibotwi** [comment]
Wow. Found another amazing feature -> evaluate selected expression on the server.
It is so nice, and saves time switching to QPad.
I there a keybinding for it?

Can you add it to list of features in readme.md? So more people can know about it :)

**Comment by a2ndrade** [comment]
The default bindings are here: https://github.com/a2ndrade/q-intellij-plugin/blob/master/src/main/resources/META-INF/plugin.xml#L268-L285 . You should be able to remap them (if you wanted different ones).

**Comment by wibotwi** [comment]
And unfortunately original issue is back :(
ctrl+shift+f does not work :(

**Comment by wibotwi** [comment]
I'll close the issue. Looks like problem was that out folder was not ignored. So Pycharm was trying to search inside it using plugin to parse Q files, but since it is changing on every build and contains lots of extra files it somehow messed up. 
After I marked "out" as "excuded" the issue went away.
