### ISSUE TITLE
Plugin ignore files with dot

### ISSUE THREAD

**Issue by wibotwi** [a2ndrade/q-intellij-plugin#57]
For example file name "load.q" is parsed and "data.load.q" is not parsed.
I have syntax highlighting in it, but ctrl+click does not navigate to functions defined in that file: neither within file nor from other files.

**Comment by a2ndrade** [comment]
Thanks for the bug report! I hope to find some time this weekend.

**Comment by a2ndrade** [comment]
@wibotwi I cannot reproduce this. Files with dots work correctly for me.  @YuriyYatsyk would you mind checking if they work for you?

**Comment by YuriyYatsyk** [comment]
Works fine for me too.

**Comment by wibotwi** [comment]
let me try to reproduce on my local PC, original issue was on work PC

**Comment by wibotwi** [comment]
PyCharm updated plugin today. And now dot files just works!
Thank you, jira is fixed :)
