### ISSUE TITLE
PyCharm reports that plugin is not compatible with 2020.2

### ISSUE THREAD

**Issue by sashkab** [a2ndrade/q-intellij-plugin#61]
![screenshot_2020 08 03_115708](https://user-images.githubusercontent.com/868842/89202124-7beed000-d580-11ea-83ee-59a4e1f5c984.png)

**Comment by a2ndrade** [comment]
Thanks, @sashkab. I will ship a new version soon.

**Comment by a2ndrade** [comment]
Support added in `v1.26`
