### ISSUE TITLE
Plugin does not load on intellij 2016.1.2

### ISSUE THREAD

**Issue by mittonsimon** [a2ndrade/q-intellij-plugin#9]
In \src\main\java\com\appian\intellij\k\KIcons.java, it references a path for the icon.  When plugin is loaded into intelliJ and you click on file types, you get an error - could not load class com.appian.intellij.k.KIcons.java.  

I had to update it to be:

``
from: IconLoader.getIcon("/com/appian/intellij/k/k.png"); 

to :    IconLoader.getIcon("icon.png");
``

Also made resources marked as resources root

**Comment by a2ndrade** [comment]
@mittonsimon sorry, I just saw this. It should be fixed now. Thanks!
